config/routes.rb
Rails.application.routes.draw do

  resources :followers do |r|
    collection do
      get 'random'
    end
  end

  get 'profile' => 'profile#index'
  patch 'profile' => 'profile#update'

  devise_for :users
  root 'home#index'

  resources :tweets, only: [:create, :index, :delete]

end

app/models/follower.rb
class Follower < ActiveRecord::Base
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  def as_json(options={})
     super(methods: [:author_name, :gravatar])
  end

  def author_name
    user.display_name
  end

  def gravatar
    user.avatar
  end

  def self.stream_for(current_user_id)
    joins(:user)
    .where(["users.id = :current_user_id or users.id in (
      select user_id from followers
      where followed_by = :current_user_id
      )", {current_user_id: current_user_id} ])
    .order(created_at: :desc)
    .all
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def as_json(options={})
      {id: id, name: display_name, gravatar: avatar}
   end

   def display_name
     first_name.present? ? "#{first_name} #{last_name}" : email
   end

   def avatar
     hash = Digest::MD5.hexdigest(email)
     "https://www.gravatar.com/avatar/#{hash}"
   end

   def self.who_to_follow(current_user_id)
     where(["id != :current_user_id and not exists (
       select 1 from followers
       where user_id = users.id
       and followed_by = :current_user_id
       )", {current_user_id: current_user_id}])
     .order("random()").all
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  def random
    render json: User.who_to_follow(current_user.id)
  end

  def create
    follower = Follower.create(user_id: params[:user_id], followed_by:current_user.id)
    render json: follower
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
  def index
    @user= current_user
  end

  def update
    current_user.update(user_params)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def index
    render json: Tweet.stream_for(current_user.id)
  end

  def create
    @tweet = Tweet.create(body: params[:body], user_id: current_user.id)
    render json: @tweet
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/home/index.html.erb
<div id="react" {prerender:true}></div>
<!-- <%= react_component ('Main'), {prerender:true}, id: 'react'%> -->

app/views/layouts/application.html.slim
doctype html
html
  head
    title TwitterLikeReact
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css"
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"
    = javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"
    = stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons"
    = csrf_meta_tags

  body
    -if notice
      p.notice = notice
    -if alert
      p.alert = alert

    .right
      - if user_signed_in?
        p Welcome #{link_to current_user.display_name, profile_path}, #{link_to 'log out', destroy_user_session_path, method: 'DELETE'}
      - else
        p Please #{link_to 'login', new_user_session_path} or #{link_to 'sign up', new_user_registration_path}

    =yield